const fallbackHomeData = {
  updatedAt: '2026-03-08T09:00:00Z',
  hero: {
    eyebrow: 'RealCommerce operations cockpit',
    title: 'Operate catalog, orders, and fulfilment from one resilient commerce stack.',
    subtitle:
      'This homepage is backed by PostgreSQL and an Express API so merchandising, warehouse activity, exchange rates, and order flow stay in one operational view.',
    primaryCta: {
      label: 'Browse featured SKUs',
      href: '#featured-products',
    },
    secondaryCta: {
      label: 'Review order flow',
      href: '#operations',
    },
  },
  highlights: [
    {
      title: 'Catalog depth',
      text: 'Products, categories, and attribute matrices are modeled in PostgreSQL for clean API reads.',
    },
    {
      title: 'Fulfilment visibility',
      text: 'Inventory sits across multiple warehouses with utilization and reorder thresholds ready for expansion.',
    },
    {
      title: 'Commercial context',
      text: 'Orders, payments, shipments, and exchange rates are linked so the homepage can surface real operating signals.',
    },
  ],
  metrics: [
    {
      label: 'Live SKUs',
      value: 6,
      detail: '5 merchandising lanes',
    },
    {
      label: 'Warehouses',
      value: 4,
      detail: '453 units on hand',
    },
    {
      label: 'Orders Routed',
      value: 6,
      detail: 'Seeded across payment and shipment states',
    },
    {
      label: 'Tracked Revenue',
      value: 5835.97,
      detail: 'Gross merchandise value in seeded data',
      kind: 'currency',
      currency: 'USD',
    },
  ],
  featuredCategories: [
    {
      id: 2,
      name: 'Connected Living',
      slug: 'connected-living',
      description: 'Smart home hardware with calm, practical interfaces.',
      heroCopy:
        'Ambient technology for homes that need less friction and more control.',
      productCount: 1,
    },
    {
      id: 5,
      name: 'Creator Gear',
      slug: 'creator-gear',
      description: 'Portable tools for production, streaming, and hybrid work.',
      heroCopy: 'Clean hardware choices for video, audio, and maker setups.',
      productCount: 1,
    },
    {
      id: 3,
      name: 'Wellness Technology',
      slug: 'wellness-technology',
      description: 'Recovery and wellbeing products for modern work rhythms.',
      heroCopy:
        'Products that make demanding work sustainable over long cycles.',
      productCount: 1,
    },
    {
      id: 1,
      name: 'Workspace Systems',
      slug: 'workspace-systems',
      description: 'Furniture and devices designed for high-output teams.',
      heroCopy:
        'Flexible setups for founders, studios, and distributed operators.',
      productCount: 2,
    },
  ],
  featuredProducts: [
    {
      id: 1,
      name: 'Atlas Standing Desk',
      slug: 'atlas-standing-desk',
      sku: 'RC-DSK-001',
      description:
        'Electric sit-stand desk with cable channel and memory presets.',
      price: 899,
      currency: 'USD',
      launchMonth: 'January 2026',
      status: 'ACTIVE',
      category: 'Workspace Systems',
      inventoryUnits: 50,
      attributes: [
        { label: 'Finish', value: 'Natural bamboo / graphite frame' },
        { label: 'Material', value: 'Steel and bamboo' },
        { label: 'Shipping Class', value: 'Freight' },
      ],
    },
    {
      id: 3,
      name: 'Pulse Smart Lamp',
      slug: 'pulse-smart-lamp',
      sku: 'RC-LMP-003',
      description:
        'Adaptive lighting with scene presets and occupancy awareness.',
      price: 129,
      currency: 'USD',
      launchMonth: 'December 2025',
      status: 'ACTIVE',
      category: 'Connected Living',
      inventoryUnits: 164,
      attributes: [
        { label: 'Connectivity', value: 'Wi-Fi + Bluetooth' },
        { label: 'Finish', value: 'Sandstone' },
        { label: 'Shipping Class', value: 'Standard parcel' },
      ],
    },
    {
      id: 4,
      name: 'Drift Noise-Canceling Buds',
      slug: 'drift-noise-canceling-buds',
      sku: 'RC-AUD-004',
      description: 'Compact earbuds for creators and focused operators.',
      price: 189,
      currency: 'USD',
      launchMonth: 'January 2026',
      status: 'ACTIVE',
      category: 'Creator Gear',
      inventoryUnits: 99,
      attributes: [
        { label: 'Battery Life', value: '36 hours' },
        { label: 'Connectivity', value: 'Bluetooth 5.4' },
        { label: 'Shipping Class', value: 'Express parcel' },
      ],
    },
    {
      id: 5,
      name: 'Tempo Recovery Massager',
      slug: 'tempo-recovery-massager',
      sku: 'RC-WEL-005',
      description:
        'Portable recovery tool with programmable pressure bands.',
      price: 249,
      currency: 'USD',
      launchMonth: 'November 2025',
      status: 'ACTIVE',
      category: 'Wellness Technology',
      inventoryUnits: 48,
      attributes: [
        { label: 'Battery Life', value: '4 hours' },
        { label: 'Material', value: 'Aluminum shell' },
        { label: 'Shipping Class', value: 'Standard parcel' },
      ],
    },
    {
      id: 6,
      name: 'Rover Fold E-Scooter',
      slug: 'rover-fold-e-scooter',
      sku: 'RC-SCO-006',
      description:
        'Foldable commuter scooter built for short urban loops.',
      price: 1499,
      currency: 'USD',
      launchMonth: 'March 2026',
      status: 'ACTIVE',
      category: 'Urban Mobility',
      inventoryUnits: 28,
      attributes: [
        { label: 'Battery Life', value: '48 km range' },
        { label: 'Material', value: 'Aluminum frame' },
        { label: 'Shipping Class', value: 'Freight' },
      ],
    },
  ],
  operations: {
    pipeline: [
      { status: 'PENDING', count: 1 },
      { status: 'PROCESSING', count: 2 },
      { status: 'PAID', count: 1 },
      { status: 'SHIPPED', count: 1 },
      { status: 'DELIVERED', count: 1 },
    ],
    recentOrders: [
      {
        orderNumber: 'RC-1001',
        customerName: 'Sofia Nwosu',
        status: 'PROCESSING',
        paymentStatus: 'CAPTURED',
        shipmentStatus: 'PACKED',
        total: 1401.39,
        currency: 'USD',
        placedAt: '2026-03-08T08:00:00Z',
      },
      {
        orderNumber: 'RC-1002',
        customerName: 'Lionel Grant',
        status: 'SHIPPED',
        paymentStatus: 'CAPTURED',
        shipmentStatus: 'IN_TRANSIT',
        total: 1658.78,
        currency: 'USD',
        placedAt: '2026-03-07T14:20:00Z',
      },
      {
        orderNumber: 'RC-1003',
        customerName: 'Clara Bennett',
        status: 'DELIVERED',
        paymentStatus: 'CAPTURED',
        shipmentStatus: 'DELIVERED',
        total: 422.46,
        currency: 'USD',
        placedAt: '2026-03-06T09:10:00Z',
      },
      {
        orderNumber: 'RC-1004',
        customerName: 'Samuel Okeke',
        status: 'PENDING',
        paymentStatus: 'PENDING',
        shipmentStatus: 'PENDING',
        total: 1781.96,
        currency: 'USD',
        placedAt: '2026-03-05T16:45:00Z',
      },
      {
        orderNumber: 'RC-1005',
        customerName: 'Sofia Nwosu',
        status: 'PROCESSING',
        paymentStatus: 'AUTHORIZED',
        shipmentStatus: 'PICKING',
        total: 279.27,
        currency: 'USD',
        placedAt: '2026-03-04T11:35:00Z',
      },
    ],
    warehouses: [
      {
        code: 'LAG-1',
        name: 'Lagos Core Fulfilment',
        city: 'Lagos',
        country: 'Nigeria',
        capacityUnits: 2600,
        quantityOnHand: 192,
        utilization: 7.4,
      },
      {
        code: 'NBO-1',
        name: 'Nairobi East Hub',
        city: 'Nairobi',
        country: 'Kenya',
        capacityUnits: 1800,
        quantityOnHand: 144,
        utilization: 8,
      },
      {
        code: 'RTM-1',
        name: 'Rotterdam Gateway',
        city: 'Rotterdam',
        country: 'Netherlands',
        capacityUnits: 3400,
        quantityOnHand: 75,
        utilization: 2.2,
      },
      {
        code: 'ACC-1',
        name: 'Accra QuickShip',
        city: 'Accra',
        country: 'Ghana',
        capacityUnits: 1200,
        quantityOnHand: 42,
        utilization: 3.5,
      },
    ],
    currencies: [
      {
        code: 'EUR',
        name: 'Euro',
        symbol: 'EUR',
        isBase: false,
        rate: 0.92,
      },
      {
        code: 'GBP',
        name: 'British Pound Sterling',
        symbol: 'GBP',
        isBase: false,
        rate: 0.78,
      },
      {
        code: 'NGN',
        name: 'Nigerian Naira',
        symbol: 'NGN',
        isBase: false,
        rate: 1542.5,
      },
      {
        code: 'USD',
        name: 'United States Dollar',
        symbol: '$',
        isBase: true,
        rate: 1,
      },
    ],
  },
};

export default fallbackHomeData;
