const fallbackData = {
  site: {
    brand: 'RealCommerce',
    tagline: 'Premium marketplace with multi-currency checkout and warehouse-aware fulfillment.',
    location: 'Douala',
    spotlightLabel: 'Shop confidently with secure checkout, live exchange rates, and real-time inventory tracking.',
    navigationLinks: [
      { label: 'Home', page: 'home' },
      { label: 'Catalog', page: 'catalog' },
      { label: 'Track order', page: 'access' },
    ],
    footerCta: {
      eyebrow: 'Built for modern commerce',
      title: 'Browse, buy, and ship with confidence.',
      copy: 'RealCommerce.com delivers a professional shopping experience with secure checkout, real-time inventory, and global fulfillment.',
    },
    footerColumns: [
      {
        title: 'Explore',
        links: [
          { label: 'Catalog', page: 'catalog' },
          { label: 'Workspace Systems', page: 'catalog', slug: 'workspace-systems' },
          { label: 'Connected Living', page: 'catalog', slug: 'connected-living' },
          { label: 'Urban Mobility', page: 'catalog', slug: 'urban-mobility' },
        ],
      },
      {
        title: 'Orders',
        links: [
          { label: 'Track an order', page: 'access' },
          { label: 'Your cart', page: 'cart' },
          { label: 'Checkout', page: 'checkout' },
          { label: 'Order history', page: 'dashboard' },
        ],
      },
      {
        title: 'Account',
        links: [
          { label: 'Sign in', page: 'login' },
          { label: 'Create account', page: 'register' },
          { label: 'Dashboard', page: 'dashboard' },
        ],
      },
      {
        title: 'Company',
        links: [
          { label: 'Home', page: 'home' },
          { label: 'Customer dashboard', page: 'dashboard' },
          { label: 'About us', page: 'home' },
        ],
      },
    ],
    seo: {
      organization: 'RealCommerce',
      returnWindowDays: 30,
    },
  },
  session: null,
  lookups: {
    categories: [
      { id: 1, name: 'Workspace Systems', slug: 'workspace-systems', description: 'Desks, seating, and operator-grade setups.' },
      { id: 2, name: 'Connected Living', slug: 'connected-living', description: 'Smart home hardware and ambient technology.' },
      { id: 3, name: 'Audio & Sound', slug: 'audio-sound', description: 'Headphones, speakers, and studio monitors.' },
      { id: 4, name: 'Urban Mobility', slug: 'urban-mobility', description: 'Scooters, bikes, and commuter essentials.' },
      { id: 5, name: 'Creator Gear', slug: 'creator-gear', description: 'Cameras, mics, and portable creator tools.' },
      { id: 6, name: 'Accessories', slug: 'accessories', description: 'Cables, cases, chargers, and peripherals.' },
    ],
    paymentMethods: [
      { id: 'card', label: 'Card', provider: 'Stripe' },
      { id: 'wallet', label: 'Wallet', provider: 'Stripe' },
      { id: 'bank_transfer', label: 'Bank transfer', provider: 'Paystack' },
    ],
    shippingMethods: [
      { id: 'standard', label: 'Standard delivery', amount: 16, eta_days: 6 },
      { id: 'priority', label: 'Priority delivery', amount: 32, eta_days: 4 },
      { id: 'freight', label: 'Freight coordination', amount: 58, eta_days: 8 },
    ],
    warehouses: [
      { id: 1, code: 'LAG-1', name: 'Lagos Core Fulfilment', city: 'Lagos', country: 'Nigeria', capacity_units: 2600, is_active: true },
      { id: 2, code: 'RTM-1', name: 'Rotterdam Gateway', city: 'Rotterdam', country: 'Netherlands', capacity_units: 3400, is_active: true },
    ],
    promotions: [
      { code: 'WELCOME10', title: 'Welcome savings', description: 'Ten percent off the first basket.' },
    ],
  },
  home: {
    heroSlides: [
      {
        id: 'atlas-standing-desk',
        eyebrow: 'Premium Electronics',
        title: 'Atlas Standing Desk',
        copy: 'Electric sit-stand desk with premium finishes and cable management.',
        imageUrl: 'https://picsum.photos/seed/3921/1200/1200',
        ctaLabel: 'Shop Now',
        categorySlug: 'workspace-systems',
      },
      {
        id: 'deals-season',
        eyebrow: 'Exclusive Deals',
        title: 'Seasonal Savings Event',
        copy: 'Premium products at unbeatable prices with multi-currency checkout.',
        imageUrl: 'https://picsum.photos/seed/4337/1200/1200',
        ctaLabel: 'View Deals',
        categorySlug: '',
      },
      {
        id: 'rover-fold-e-scooter',
        eyebrow: 'Urban Mobility',
        title: 'Rover Fold E-Scooter',
        copy: 'A foldable commuter scooter built for short urban loops.',
        imageUrl: 'https://picsum.photos/seed/4730/1200/1200',
        ctaLabel: 'Explore',
        categorySlug: 'urban-mobility',
      },
      {
        id: 'fast-shipping',
        eyebrow: 'Free Shipping',
        title: 'Free Express Delivery',
        copy: 'Orders over $1,200 ship free from our global warehouse network.',
        imageUrl: 'https://picsum.photos/seed/5136/1200/1200',
        ctaLabel: 'Start Shopping',
        categorySlug: '',
      },
    ],
    featuredCategories: [
      { id: 1, name: 'Workspace Systems', slug: 'workspace-systems', description: 'Flexible setups for focused teams.' },
      { id: 2, name: 'Connected Living', slug: 'connected-living', description: 'Ambient technology with calm interfaces.' },
      { id: 3, name: 'Audio & Sound', slug: 'audio-sound', description: 'Professional and personal audio gear.' },
      { id: 4, name: 'Urban Mobility', slug: 'urban-mobility', description: 'Reliable products for city movement.' },
      { id: 5, name: 'Creator Gear', slug: 'creator-gear', description: 'Tools for content creation.' },
      { id: 6, name: 'Accessories', slug: 'accessories', description: 'Essential add-ons and peripherals.' },
    ],
    featuredProducts: [
      {
        id: 1, name: 'Atlas Standing Desk', slug: 'atlas-standing-desk',
        category_name: 'Workspace Systems', category_slug: 'workspace-systems',
        short_description: 'Electric sit-stand desk with cable channel and memory presets.',
        unit_price: 899, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/6115/600/600',
        average_rating: 4.8, review_count: 218, available_units: 50,
        store_name: 'Studio Forge',
      },
      {
        id: 2, name: 'Ergonomic Office Chair', slug: 'ergonomic-office-chair',
        category_name: 'Workspace Systems', category_slug: 'workspace-systems',
        short_description: 'Mesh-back office chair with lumbar support and adjustable arms.',
        unit_price: 549, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/6660/600/600',
        average_rating: 4.5, review_count: 142, available_units: 35,
        store_name: 'Studio Forge',
      },
      {
        id: 3, name: 'Pulse Smart Lamp', slug: 'pulse-smart-lamp',
        category_name: 'Connected Living', category_slug: 'connected-living',
        short_description: 'Adaptive lighting with scene presets and occupancy awareness.',
        unit_price: 129, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/7187/600/600',
        average_rating: 4.4, review_count: 87, available_units: 74,
        store_name: 'Studio Forge',
      },
      {
        id: 4, name: 'Drift Noise-Canceling Buds', slug: 'drift-noise-canceling-buds',
        category_name: 'Audio & Sound', category_slug: 'audio-sound',
        short_description: 'Compact earbuds with active noise canceling and 28-hour battery.',
        unit_price: 189, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/7730/600/600',
        average_rating: 4.9, review_count: 311, available_units: 99,
        store_name: 'Studio Forge',
      },
      {
        id: 5, name: 'Wireless Charging Pad', slug: 'wireless-charging-pad',
        category_name: 'Accessories', category_slug: 'accessories',
        short_description: '15W fast wireless charger with LED indicator and anti-slip base.',
        unit_price: 39, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/8259/600/600',
        average_rating: 4.3, review_count: 56, available_units: 200,
        store_name: 'Mobility Works',
      },
      {
        id: 6, name: 'Rover Fold E-Scooter', slug: 'rover-fold-e-scooter',
        category_name: 'Urban Mobility', category_slug: 'urban-mobility',
        short_description: 'Foldable commuter scooter with 25km range and disc brakes.',
        unit_price: 1499, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/8790/600/600',
        average_rating: 4.6, review_count: 63, available_units: 12,
        store_name: 'Mobility Works',
      },
      {
        id: 7, name: 'Studio Monitor Headphones', slug: 'studio-monitor-headphones',
        category_name: 'Audio & Sound', category_slug: 'audio-sound',
        short_description: 'Over-ear studio headphones with flat frequency response.',
        unit_price: 279, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/9325/600/600',
        average_rating: 4.7, review_count: 195, available_units: 44,
        store_name: 'Studio Forge',
      },
      {
        id: 8, name: 'Smart Thermostat Pro', slug: 'smart-thermostat-pro',
        category_name: 'Connected Living', category_slug: 'connected-living',
        short_description: 'Wi-Fi thermostat with learning algorithm and energy reports.',
        unit_price: 199, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/9859/600/600',
        average_rating: 4.2, review_count: 73, available_units: 60,
        store_name: 'Studio Forge',
      },
      {
        id: 9, name: '4K Webcam Pro', slug: '4k-webcam-pro',
        category_name: 'Creator Gear', category_slug: 'creator-gear',
        short_description: '4K 60fps webcam with auto-framing and built-in ring light.',
        unit_price: 159, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/10368/600/600',
        average_rating: 4.6, review_count: 124, available_units: 88,
        store_name: 'Studio Forge',
      },
      {
        id: 10, name: 'Mechanical Keyboard', slug: 'mechanical-keyboard',
        category_name: 'Workspace Systems', category_slug: 'workspace-systems',
        short_description: 'Low-profile mechanical keyboard with hot-swappable switches.',
        unit_price: 149, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/10903/600/600',
        average_rating: 4.8, review_count: 267, available_units: 120,
        store_name: 'Studio Forge',
      },
      {
        id: 11, name: 'Portable Power Bank', slug: 'portable-power-bank',
        category_name: 'Accessories', category_slug: 'accessories',
        short_description: '20000mAh portable charger with USB-C PD and dual output.',
        unit_price: 59, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/11422/600/600',
        average_rating: 4.4, review_count: 189, available_units: 300,
        store_name: 'Mobility Works',
      },
      {
        id: 12, name: 'City Commuter Bike', slug: 'city-commuter-bike',
        category_name: 'Urban Mobility', category_slug: 'urban-mobility',
        short_description: 'Lightweight alloy frame city bike with 7-speed Shimano gears.',
        unit_price: 699, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/11953/600/600',
        average_rating: 4.5, review_count: 48, available_units: 18,
        store_name: 'Mobility Works',
      },
      {
        id: 13, name: 'USB-C Hub 8-in-1', slug: 'usb-c-hub-8in1',
        category_name: 'Accessories', category_slug: 'accessories',
        short_description: '8-port USB-C hub with HDMI 4K, SD reader, and 100W PD pass-through.',
        unit_price: 79, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/12473/600/600',
        average_rating: 4.3, review_count: 93, available_units: 150,
        store_name: 'Studio Forge',
      },
      {
        id: 14, name: 'Condenser Microphone', slug: 'condenser-microphone',
        category_name: 'Creator Gear', category_slug: 'creator-gear',
        short_description: 'Cardioid condenser USB mic with pop filter and desk mount.',
        unit_price: 119, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/12998/600/600',
        average_rating: 4.7, review_count: 156, available_units: 65,
        store_name: 'Studio Forge',
      },
      {
        id: 15, name: 'Bluetooth Speaker', slug: 'bluetooth-speaker',
        category_name: 'Audio & Sound', category_slug: 'audio-sound',
        short_description: 'Waterproof portable Bluetooth speaker with 24h battery life.',
        unit_price: 89, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/13518/600/600',
        average_rating: 4.5, review_count: 234, available_units: 180,
        store_name: 'Studio Forge',
      },
      {
        id: 16, name: 'Smart Security Camera', slug: 'smart-security-camera',
        category_name: 'Connected Living', category_slug: 'connected-living',
        short_description: '2K indoor/outdoor camera with night vision and two-way audio.',
        unit_price: 79, currency_code: 'USD',
        image_url: 'https://picsum.photos/seed/14056/600/600',
        average_rating: 4.1, review_count: 102, available_units: 90,
        store_name: 'Studio Forge',
      },
    ],
    orderPipeline: [
      { label: 'PROCESSING', value: 2 },
      { label: 'SHIPPED', value: 1 },
      { label: 'DELIVERED', value: 1 },
    ],
    warehouses: [
      { id: 1, name: 'Lagos Core Fulfilment', city: 'Lagos', country: 'Nigeria', utilized_units: 1820, capacity_units: 2600, utilizationRate: 70 },
      { id: 2, name: 'Rotterdam Gateway', city: 'Rotterdam', country: 'Netherlands', utilized_units: 2240, capacity_units: 3400, utilizationRate: 66 },
    ],
    valueProps: [
      { title: 'Fast, free delivery', copy: 'Free shipping on eligible orders over the platform threshold.' },
      { title: 'Easy returns', copy: 'Return most items within 30 days. No questions asked.' },
      { title: 'Secure checkout', copy: '256-bit SSL encryption. Your payment info is always protected.' },
      { title: 'Multiple currencies', copy: 'Shop and pay in your preferred currency at live rates.' },
    ],
    testimonials: [
      { rating: 5, title: 'Great for creator workflows', body: 'Battery life and microphone clarity have been excellent.', customer_name: 'Sofia N.' },
      { rating: 5, title: 'Professional platform', body: 'The storefront and checkout experience feel world-class.', customer_name: 'James K.' },
    ],
  },
  products: [
    { id: 1, name: 'Atlas Standing Desk', slug: 'atlas-standing-desk', category_name: 'Workspace Systems', category_slug: 'workspace-systems', short_description: 'Electric sit-stand desk with cable channel and memory presets.', unit_price: 899, currency_code: 'USD', image_url: 'https://picsum.photos/seed/15815/600/600', average_rating: 4.8, review_count: 218, available_units: 50, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 2, name: 'Ergonomic Office Chair', slug: 'ergonomic-office-chair', category_name: 'Workspace Systems', category_slug: 'workspace-systems', short_description: 'Mesh-back office chair with lumbar support and adjustable arms.', unit_price: 549, currency_code: 'USD', image_url: 'https://picsum.photos/seed/16313/600/600', average_rating: 4.5, review_count: 142, available_units: 35, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 3, name: 'Pulse Smart Lamp', slug: 'pulse-smart-lamp', category_name: 'Connected Living', category_slug: 'connected-living', short_description: 'Adaptive lighting with scene presets and occupancy awareness.', unit_price: 129, currency_code: 'USD', image_url: 'https://picsum.photos/seed/16793/600/600', average_rating: 4.4, review_count: 87, available_units: 74, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 4, name: 'Drift Noise-Canceling Buds', slug: 'drift-noise-canceling-buds', category_name: 'Audio & Sound', category_slug: 'audio-sound', short_description: 'Compact earbuds with active noise canceling and 28-hour battery.', unit_price: 189, currency_code: 'USD', image_url: 'https://picsum.photos/seed/17289/600/600', average_rating: 4.9, review_count: 311, available_units: 99, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 5, name: 'Wireless Charging Pad', slug: 'wireless-charging-pad', category_name: 'Accessories', category_slug: 'accessories', short_description: '15W fast wireless charger with LED indicator and anti-slip base.', unit_price: 39, currency_code: 'USD', image_url: 'https://picsum.photos/seed/17771/600/600', average_rating: 4.3, review_count: 56, available_units: 200, store_name: 'Mobility Works', status: 'ACTIVE' },
    { id: 6, name: 'Rover Fold E-Scooter', slug: 'rover-fold-e-scooter', category_name: 'Urban Mobility', category_slug: 'urban-mobility', short_description: 'Foldable commuter scooter with 25km range and disc brakes.', unit_price: 1499, currency_code: 'USD', image_url: 'https://picsum.photos/seed/18255/600/600', average_rating: 4.6, review_count: 63, available_units: 12, store_name: 'Mobility Works', status: 'ACTIVE' },
    { id: 7, name: 'Studio Monitor Headphones', slug: 'studio-monitor-headphones', category_name: 'Audio & Sound', category_slug: 'audio-sound', short_description: 'Over-ear studio headphones with flat frequency response.', unit_price: 279, currency_code: 'USD', image_url: 'https://picsum.photos/seed/18743/600/600', average_rating: 4.7, review_count: 195, available_units: 44, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 8, name: 'Smart Thermostat Pro', slug: 'smart-thermostat-pro', category_name: 'Connected Living', category_slug: 'connected-living', short_description: 'Wi-Fi thermostat with learning algorithm and energy reports.', unit_price: 199, currency_code: 'USD', image_url: 'https://picsum.photos/seed/19230/600/600', average_rating: 4.2, review_count: 73, available_units: 60, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 9, name: '4K Webcam Pro', slug: '4k-webcam-pro', category_name: 'Creator Gear', category_slug: 'creator-gear', short_description: '4K 60fps webcam with auto-framing and built-in ring light.', unit_price: 159, currency_code: 'USD', image_url: 'https://picsum.photos/seed/19692/600/600', average_rating: 4.6, review_count: 124, available_units: 88, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 10, name: 'Mechanical Keyboard', slug: 'mechanical-keyboard', category_name: 'Workspace Systems', category_slug: 'workspace-systems', short_description: 'Low-profile mechanical keyboard with hot-swappable switches.', unit_price: 149, currency_code: 'USD', image_url: 'https://picsum.photos/seed/20180/600/600', average_rating: 4.8, review_count: 267, available_units: 120, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 11, name: 'Portable Power Bank', slug: 'portable-power-bank', category_name: 'Accessories', category_slug: 'accessories', short_description: '20000mAh portable charger with USB-C PD and dual output.', unit_price: 59, currency_code: 'USD', image_url: 'https://picsum.photos/seed/20652/600/600', average_rating: 4.4, review_count: 189, available_units: 300, store_name: 'Mobility Works', status: 'ACTIVE' },
    { id: 12, name: 'City Commuter Bike', slug: 'city-commuter-bike', category_name: 'Urban Mobility', category_slug: 'urban-mobility', short_description: 'Lightweight alloy frame city bike with 7-speed gears.', unit_price: 699, currency_code: 'USD', image_url: 'https://picsum.photos/seed/21128/600/600', average_rating: 4.5, review_count: 48, available_units: 18, store_name: 'Mobility Works', status: 'ACTIVE' },
    { id: 13, name: 'USB-C Hub 8-in-1', slug: 'usb-c-hub-8in1', category_name: 'Accessories', category_slug: 'accessories', short_description: '8-port USB-C hub with HDMI 4K, SD reader, and 100W PD.', unit_price: 79, currency_code: 'USD', image_url: 'https://picsum.photos/seed/21588/600/600', average_rating: 4.3, review_count: 93, available_units: 150, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 14, name: 'Condenser Microphone', slug: 'condenser-microphone', category_name: 'Creator Gear', category_slug: 'creator-gear', short_description: 'Cardioid condenser USB mic with pop filter and desk mount.', unit_price: 119, currency_code: 'USD', image_url: 'https://picsum.photos/seed/22066/600/600', average_rating: 4.7, review_count: 156, available_units: 65, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 15, name: 'Bluetooth Speaker', slug: 'bluetooth-speaker', category_name: 'Audio & Sound', category_slug: 'audio-sound', short_description: 'Waterproof portable Bluetooth speaker with 24h battery.', unit_price: 89, currency_code: 'USD', image_url: 'https://picsum.photos/seed/22534/600/600', average_rating: 4.5, review_count: 234, available_units: 180, store_name: 'Studio Forge', status: 'ACTIVE' },
    { id: 16, name: 'Smart Security Camera', slug: 'smart-security-camera', category_name: 'Connected Living', category_slug: 'connected-living', short_description: '2K indoor/outdoor camera with night vision and two-way audio.', unit_price: 79, currency_code: 'USD', image_url: 'https://picsum.photos/seed/23025/600/600', average_rating: 4.1, review_count: 102, available_units: 90, store_name: 'Studio Forge', status: 'ACTIVE' },
  ],
};

export default fallbackData;
